"""
Pydantic models for the neonatal patient record system.
Includes both structured clinical fields AND dashboard display data,
all generated by the LLM from free-text reports.
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
import uuid


# ═══════════════════════════════════════════════════
# Dashboard display models (consumed by React frontend)
# ═══════════════════════════════════════════════════

class DashboardRiskScore(BaseModel):
    label: str = ""
    horizon: str = ""
    level: str = "low"
    probabilityRange: str = ""
    trend: str = "stable"
    delta: str = ""
    details: Optional[str] = None

class DashboardContributingFactor(BaseModel):
    id: str = ""
    text: str = ""
    trend: str = "stable"
    dataSnippet: str = ""
    noteExcerpt: str = ""
    similarCaseSummary: str = ""

class DashboardVitalDataPoint(BaseModel):
    timestamp: str = ""
    value: float = 0

class DashboardVitalSeries(BaseModel):
    label: str = ""
    unit: str = ""
    color: str = "#60a5fa"
    data: list[DashboardVitalDataPoint] = []

class DashboardIntervention(BaseModel):
    timestamp: str = ""
    label: str = ""
    icon: str = "💊"
    type: str = ""

class DashboardSimilarCase(BaseModel):
    id: str = ""
    ga: float = 0
    bw: float = 0
    mainIssue: str = ""
    outcomeSummary: str = ""
    timeToEvent: str = ""
    similarityScore: float = 0
    details: str = ""

class DashboardClinicalInterpretation(BaseModel):
    summary: str = ""
    uncertaintyFlags: list[str] = []

class DashboardData(BaseModel):
    """All data required by the React dashboard to render a patient."""
    name: str = ""
    mrn: str = ""
    ga: float = 0
    bw: float = 0
    dob: str = ""
    admissionDate: str = ""
    currentSupport: str = "Room Air"
    sex: str = ""
    dayOfLife: int = 0
    overallRisk: str = "low"
    overallTrend: str = "stable"
    risks: list[DashboardRiskScore] = []
    contributingFactors: list[DashboardContributingFactor] = []
    vitals: list[DashboardVitalSeries] = []
    interventions: list[DashboardIntervention] = []
    similarCases: list[DashboardSimilarCase] = []
    clinicalInterpretation: DashboardClinicalInterpretation = DashboardClinicalInterpretation()


# ═══════════════════════════════════════════════════
# Structured clinical record (70+ fields)
# ═══════════════════════════════════════════════════

class PatientRecord(BaseModel):
    """Structured patient record with all 70+ clinical fields."""

    date_entree: Optional[str] = Field(None, alias="date_entrée")
    date_deces: Optional[str] = Field(None, alias="date_décès")
    date_sortie: Optional[str] = Field(None)
    sexe_nouveau_ne: Optional[str] = Field(None, alias="sexe_nouveau_né")
    date_naissance: Optional[str] = Field(None)
    type_mariage: Optional[str] = Field(None)
    degre_consanguinite: Optional[str] = Field(None, alias="degré_consanguinité")
    ville_origine: Optional[str] = Field(None)
    ville_actuelle: Optional[str] = Field(None)
    couverture_sanitaire: Optional[str] = Field(None)
    admis_quel_jour: Optional[str] = Field(None)
    age_mere: Optional[str] = Field(None, alias="âge_mère")
    nombre_fausses_accouchement: Optional[str] = Field(None)
    type_grossesse: Optional[str] = Field(None)
    suivi_grossesse: Optional[str] = Field(None)
    grossesse_menee_a_terme: Optional[str] = Field(None, alias="grossesse_mené_à_terme")
    dubowitz: Optional[str] = Field(None)
    type_accouchement: Optional[str] = Field(None)
    voie_accouchement: Optional[str] = Field(None)
    anamnese_infectieuse: Optional[str] = Field(None, alias="anamnèse_infectieuse")
    groupage_maman: Optional[str] = Field(None)
    apgar_naissance: Optional[str] = Field(None, alias="APGAR_naissance")
    couleur: Optional[str] = Field(None)
    tonicite: Optional[str] = Field(None, alias="tonicité")
    reactivite: Optional[str] = Field(None, alias="réactivité")
    rsd: Optional[str] = Field(None, alias="RSD")
    ra: Optional[str] = Field(None, alias="RA")
    hemodynamique_fc: Optional[str] = Field(None, alias="hémodynamique_FC")
    hemodynamique_trc: Optional[str] = Field(None, alias="hémodynamique_TRC")
    respiratoire_ss: Optional[str] = Field(None, alias="respiratoire_SS")
    respiratoire_sao2: Optional[str] = Field(None, alias="respiratoire_SaO2")
    respiratoire_fr: Optional[str] = Field(None, alias="respiratoire_FR")
    glycemie_capillaire: Optional[str] = Field(None, alias="glycémie_capillaire")
    poids: Optional[str] = Field(None)
    taille: Optional[str] = Field(None)
    perimetre_cranien: Optional[str] = Field(None, alias="périmètre_crânien")
    mv: Optional[str] = Field(None, alias="MV")
    rales_auscultation: Optional[str] = Field(None, alias="râles_auscultation")
    thorax_morphologie: Optional[str] = Field(None)
    abdomen: Optional[str] = Field(None)
    masse_palpable: Optional[str] = Field(None)
    hsmg: Optional[str] = Field(None, alias="HSMG")
    b1b2: Optional[str] = Field(None, alias="B1B2")
    souffle_surajoute: Optional[str] = Field(None, alias="souffle_surajouté")
    bruits_surajoutes: Optional[str] = Field(None, alias="bruits_surajoutés")
    hb: Optional[str] = Field(None, alias="Hb")
    oge_sexe: Optional[str] = Field(None, alias="OGE_sexe")
    testicules: Optional[str] = Field(None)
    bilan_malformatif: Optional[str] = Field(None)
    radio_thorax: Optional[str] = Field(None)
    mec: Optional[str] = Field(None, alias="MEC")
    nfs_hb: Optional[str] = Field(None, alias="NFS_hb")
    plaquettes: Optional[str] = Field(None)
    uree: Optional[str] = Field(None, alias="urée")
    creat: Optional[str] = Field(None, alias="créat")
    ionogramme_nat: Optional[str] = Field(None, alias="ionogramme_Nat")
    ionogramme_k_plus: Optional[str] = Field(None, alias="ionogramme_K_plus")
    ionogramme_aib: Optional[str] = Field(None, alias="ionogramme_AÏb")
    gb: Optional[str] = Field(None, alias="GB")
    etf: Optional[str] = Field(None, alias="ETF")
    pnn: Optional[str] = Field(None, alias="PNN")
    cpk: Optional[str] = Field(None, alias="CPK")
    ecbu: Optional[str] = Field(None, alias="ECBU")
    valeur_ecbu: Optional[str] = Field(None, alias="valeur_ECBU")
    lymphopenie: Optional[str] = Field(None, alias="lymphopénie")
    crp: Optional[str] = Field(None, alias="CRP")
    controle_apres: Optional[str] = Field(None, alias="contrôlé_âpres")
    ldh: Optional[str] = Field(None, alias="LDH")
    calcemie: Optional[str] = Field(None, alias="calcémie")
    albuminemie: Optional[str] = Field(None, alias="albuminémie")
    tp: Optional[str] = Field(None, alias="TP")
    decede: Optional[str] = Field(None, alias="décédé")

    model_config = {"populate_by_name": True}


# ═══════════════════════════════════════════════════
# API request / response
# ═══════════════════════════════════════════════════

class ReportSubmission(BaseModel):
    report_text: str = Field(..., min_length=10)

class PatientRecordResponse(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    raw_report: str = ""
    record: dict = {}
    dashboard: dict = {}

    model_config = {"populate_by_name": True}
